/* Generated By:JavaCC: Do not edit this line. ComPHPConstants.java */
package compilador;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ComPHPConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PHP = 5;
  /** RegularExpression Id. */
  int IF = 6;
  /** RegularExpression Id. */
  int ELSE = 7;
  /** RegularExpression Id. */
  int ELSEIF = 8;
  /** RegularExpression Id. */
  int SWITCH = 9;
  /** RegularExpression Id. */
  int CASE = 10;
  /** RegularExpression Id. */
  int DEF = 11;
  /** RegularExpression Id. */
  int FOR = 12;
  /** RegularExpression Id. */
  int FOREACH = 13;
  /** RegularExpression Id. */
  int WHILE = 14;
  /** RegularExpression Id. */
  int DO = 15;
  /** RegularExpression Id. */
  int BREAK = 16;
  /** RegularExpression Id. */
  int CONTINUE = 17;
  /** RegularExpression Id. */
  int ENDFOR = 18;
  /** RegularExpression Id. */
  int ENDWHILE = 19;
  /** RegularExpression Id. */
  int GOTO = 20;
  /** RegularExpression Id. */
  int FUNCTION = 21;
  /** RegularExpression Id. */
  int ARREGLO = 22;
  /** RegularExpression Id. */
  int ECHO = 23;
  /** RegularExpression Id. */
  int INCLUDE = 24;
  /** RegularExpression Id. */
  int INCLUDEONCE = 25;
  /** RegularExpression Id. */
  int REQUIRE = 26;
  /** RegularExpression Id. */
  int REQUIREONCE = 27;
  /** RegularExpression Id. */
  int MAS = 28;
  /** RegularExpression Id. */
  int MENOS = 29;
  /** RegularExpression Id. */
  int MULTI = 30;
  /** RegularExpression Id. */
  int DIV = 31;
  /** RegularExpression Id. */
  int MOD = 32;
  /** RegularExpression Id. */
  int IGUAL = 33;
  /** RegularExpression Id. */
  int MASIGUAL = 34;
  /** RegularExpression Id. */
  int MENOSIGUAL = 35;
  /** RegularExpression Id. */
  int MULTIIGUAL = 36;
  /** RegularExpression Id. */
  int DIVIGUAL = 37;
  /** RegularExpression Id. */
  int MODIGUAL = 38;
  /** RegularExpression Id. */
  int PUNTOIGUAL = 39;
  /** RegularExpression Id. */
  int INCREMENTO = 40;
  /** RegularExpression Id. */
  int DECREMENTO = 41;
  /** RegularExpression Id. */
  int AND = 42;
  /** RegularExpression Id. */
  int OR = 43;
  /** RegularExpression Id. */
  int NEGACION = 44;
  /** RegularExpression Id. */
  int XOR = 45;
  /** RegularExpression Id. */
  int IGUALDAD = 46;
  /** RegularExpression Id. */
  int NOIGUALDAD = 47;
  /** RegularExpression Id. */
  int IDENTICO = 48;
  /** RegularExpression Id. */
  int NOIDENTICO = 49;
  /** RegularExpression Id. */
  int MENOR = 50;
  /** RegularExpression Id. */
  int MAYOR = 51;
  /** RegularExpression Id. */
  int MENORIGUAL = 52;
  /** RegularExpression Id. */
  int MAYORIGUAL = 53;
  /** RegularExpression Id. */
  int QUERY = 54;
  /** RegularExpression Id. */
  int DOLLAR = 55;
  /** RegularExpression Id. */
  int KOP = 56;
  /** RegularExpression Id. */
  int KCL = 57;
  /** RegularExpression Id. */
  int BOP = 58;
  /** RegularExpression Id. */
  int BCL = 59;
  /** RegularExpression Id. */
  int POP = 60;
  /** RegularExpression Id. */
  int PCL = 61;
  /** RegularExpression Id. */
  int PC = 62;
  /** RegularExpression Id. */
  int COM = 63;
  /** RegularExpression Id. */
  int PP = 64;
  /** RegularExpression Id. */
  int digito = 65;
  /** RegularExpression Id. */
  int letra = 66;
  /** RegularExpression Id. */
  int VALOR_INT = 67;
  /** RegularExpression Id. */
  int VALOR_DOUBLE = 68;
  /** RegularExpression Id. */
  int VALOR_BOOLEAN = 69;
  /** RegularExpression Id. */
  int VALOR_STRING = 70;
  /** RegularExpression Id. */
  int ID_FUNCION = 71;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 72;
  /** RegularExpression Id. */
  int ARRAY = 73;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\"php\"",
    "\"if\"",
    "\"else\"",
    "\"elseif\"",
    "\"switch\"",
    "\"case\"",
    "\"default\"",
    "\"for\"",
    "\"foreach\"",
    "\"while\"",
    "\"do\"",
    "\"break\"",
    "\"continue\"",
    "\"endfor\"",
    "\"endwhile\"",
    "\"goto\"",
    "\"function\"",
    "\"array\"",
    "\"echo\"",
    "\"include\"",
    "\"include_once\"",
    "\"require\"",
    "\"require_once\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"=\"",
    "<MASIGUAL>",
    "<MENOSIGUAL>",
    "<MULTIIGUAL>",
    "<DIVIGUAL>",
    "<MODIGUAL>",
    "<PUNTOIGUAL>",
    "<INCREMENTO>",
    "<DECREMENTO>",
    "<AND>",
    "<OR>",
    "\"!\"",
    "\"xor\"",
    "<IGUALDAD>",
    "<NOIGUALDAD>",
    "<IDENTICO>",
    "<NOIDENTICO>",
    "\"<\"",
    "\">\"",
    "<MENORIGUAL>",
    "<MAYORIGUAL>",
    "\"?\"",
    "\"$\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\",\"",
    "\":\"",
    "<digito>",
    "<letra>",
    "<VALOR_INT>",
    "<VALOR_DOUBLE>",
    "<VALOR_BOOLEAN>",
    "<VALOR_STRING>",
    "<ID_FUNCION>",
    "<IDENTIFICADOR>",
    "<ARRAY>",
  };

}
