/* Generated By:JavaCC: Do not edit this line. ComPHPConstants.java */
package compilador;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ComPHPConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PHP = 5;
  /** RegularExpression Id. */
  int IF = 6;
  /** RegularExpression Id. */
  int ELSE = 7;
  /** RegularExpression Id. */
  int ELSEIF = 8;
  /** RegularExpression Id. */
  int SWITCH = 9;
  /** RegularExpression Id. */
  int CASE = 10;
  /** RegularExpression Id. */
  int DEF = 11;
  /** RegularExpression Id. */
  int FOR = 12;
  /** RegularExpression Id. */
  int FOREACH = 13;
  /** RegularExpression Id. */
  int WHILE = 14;
  /** RegularExpression Id. */
  int DO = 15;
  /** RegularExpression Id. */
  int BREAK = 16;
  /** RegularExpression Id. */
  int CONTINUE = 17;
  /** RegularExpression Id. */
  int ENDFOR = 18;
  /** RegularExpression Id. */
  int INCLUDE = 19;
  /** RegularExpression Id. */
  int INCLUDEONCE = 20;
  /** RegularExpression Id. */
  int REQUIRE = 21;
  /** RegularExpression Id. */
  int REQUIREONCE = 22;
  /** RegularExpression Id. */
  int MAS = 23;
  /** RegularExpression Id. */
  int MENOS = 24;
  /** RegularExpression Id. */
  int MULTI = 25;
  /** RegularExpression Id. */
  int DIV = 26;
  /** RegularExpression Id. */
  int MOD = 27;
  /** RegularExpression Id. */
  int IGUAL = 28;
  /** RegularExpression Id. */
  int MASIGUAL = 29;
  /** RegularExpression Id. */
  int MENOSIGUAL = 30;
  /** RegularExpression Id. */
  int MULTIIGUAL = 31;
  /** RegularExpression Id. */
  int DIVIGUAL = 32;
  /** RegularExpression Id. */
  int MODIGUAL = 33;
  /** RegularExpression Id. */
  int PUNTOIGUAL = 34;
  /** RegularExpression Id. */
  int INCREMENTO = 35;
  /** RegularExpression Id. */
  int DECREMENTO = 36;
  /** RegularExpression Id. */
  int AND = 37;
  /** RegularExpression Id. */
  int OR = 38;
  /** RegularExpression Id. */
  int NEGACION = 39;
  /** RegularExpression Id. */
  int XOR = 40;
  /** RegularExpression Id. */
  int IGUALDAD = 41;
  /** RegularExpression Id. */
  int NOIGUALDAD = 42;
  /** RegularExpression Id. */
  int IDENTICO = 43;
  /** RegularExpression Id. */
  int NOIDENTICO = 44;
  /** RegularExpression Id. */
  int MENOR = 45;
  /** RegularExpression Id. */
  int MAYOR = 46;
  /** RegularExpression Id. */
  int MENORIGUAL = 47;
  /** RegularExpression Id. */
  int MAYORIGUAL = 48;
  /** RegularExpression Id. */
  int QUERY = 49;
  /** RegularExpression Id. */
  int DOLLAR = 50;
  /** RegularExpression Id. */
  int KOP = 51;
  /** RegularExpression Id. */
  int KCL = 52;
  /** RegularExpression Id. */
  int BOP = 53;
  /** RegularExpression Id. */
  int BCL = 54;
  /** RegularExpression Id. */
  int POP = 55;
  /** RegularExpression Id. */
  int PCL = 56;
  /** RegularExpression Id. */
  int PC = 57;
  /** RegularExpression Id. */
  int PP = 58;
  /** RegularExpression Id. */
  int digito = 59;
  /** RegularExpression Id. */
  int letra = 60;
  /** RegularExpression Id. */
  int VALOR_INT = 61;
  /** RegularExpression Id. */
  int VALOR_DOULE = 62;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 63;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\"php\"",
    "\"if\"",
    "\"else\"",
    "\"elseif\"",
    "\"switch\"",
    "\"case\"",
    "\"default\"",
    "\"for\"",
    "\"foreach\"",
    "\"while\"",
    "\"do\"",
    "\"break\"",
    "\"continue\"",
    "\"endfor\"",
    "\"include\"",
    "\"include_once\"",
    "\"require\"",
    "\"require_once\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"=\"",
    "<MASIGUAL>",
    "<MENOSIGUAL>",
    "<MULTIIGUAL>",
    "<DIVIGUAL>",
    "<MODIGUAL>",
    "<PUNTOIGUAL>",
    "<INCREMENTO>",
    "<DECREMENTO>",
    "<AND>",
    "<OR>",
    "\"!\"",
    "\"xor\"",
    "<IGUALDAD>",
    "<NOIGUALDAD>",
    "<IDENTICO>",
    "<NOIDENTICO>",
    "\"<\"",
    "\">\"",
    "<MENORIGUAL>",
    "<MAYORIGUAL>",
    "\"?\"",
    "\"$\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\":\"",
    "<digito>",
    "<letra>",
    "<VALOR_INT>",
    "<VALOR_DOULE>",
    "<IDENTIFICADOR>",
  };

}
